import jsPDF from 'jspdf'

/**
 * Generate and download a PDF forensic report.
 */
export function downloadReport(result) {
    const doc = new jsPDF()
    const verdict = result.verdict || result.label || 'UNKNOWN'
    const confidence = result.confidence || result.probability || 0
    const pct = (confidence * 100).toFixed(1)
    const reasoning = result.reasoning || 'No reasoning available.'
    const isReal = verdict === 'REAL'

    const now = new Date()
    const timestamp = now.toLocaleString()

    let y = 20

    // Header bar
    doc.setFillColor(17, 17, 17)
    doc.rect(0, 0, 210, 40, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.setTextColor(255, 255, 255)
    doc.text('Polyglot Ghost', 20, 18)
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text('Voice Deepfake Detection Report', 20, 28)
    doc.text(timestamp, 190, 28, { align: 'right' })

    y = 55

    // Verdict
    if (isReal) {
        doc.setFillColor(236, 253, 245)
        doc.setDrawColor(5, 150, 105)
    } else {
        doc.setFillColor(254, 242, 242)
        doc.setDrawColor(220, 38, 38)
    }
    doc.setLineWidth(0.5)
    doc.roundedRect(20, y, 170, 30, 3, 3, 'FD')

    doc.setFontSize(22)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(isReal ? 5 : 220, isReal ? 150 : 38, isReal ? 105 : 38)
    doc.text(verdict, 30, y + 15)

    doc.setFontSize(14)
    doc.setFont('helvetica', 'normal')
    doc.text(`${pct}% confidence`, 80, y + 15)

    y += 40

    // Separator
    doc.setDrawColor(229, 231, 235)
    doc.setLineWidth(0.3)
    doc.line(20, y, 190, y)
    y += 10

    // Analysis section
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(26, 26, 26)
    doc.text('Analysis Summary', 20, y)
    y += 8

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(107, 114, 128)

    // Word wrap reasoning
    const reasonLines = doc.splitTextToSize(reasoning, 160)
    doc.text(reasonLines, 20, y)
    y += reasonLines.length * 5 + 10

    // Separator
    doc.line(20, y, 190, y)
    y += 10

    // Technical details
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(26, 26, 26)
    doc.text('Technical Details', 20, y)
    y += 8

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(107, 114, 128)

    const details = [
        ['Detection Engine', result.model_used || 'wav2vec2 Deep Learning'],
        ['Verdict', verdict],
        ['Confidence', `${pct}%`],
        ['AI Voice Probability', result.ai_voice_prob ? `${(result.ai_voice_prob * 100).toFixed(1)}%` : 'N/A'],
        ['Human Voice Probability', result.human_voice_prob ? `${(result.human_voice_prob * 100).toFixed(1)}%` : 'N/A'],
    ]

    // Add measurements if available
    const m = result.measurements
    if (m) {
        if (m.pitch_std_hz !== undefined) details.push(['Pitch Std Dev', `${m.pitch_std_hz} Hz`])
        if (m.spectral_centroid_std !== undefined) details.push(['Spectral Centroid Std', `${m.spectral_centroid_std}`])
        if (m.rms_dynamic_range !== undefined) details.push(['RMS Dynamic Range', `${m.rms_dynamic_range}`])
        if (m.silence_noise_level !== undefined) details.push(['Silence Noise Level', `${m.silence_noise_level}`])
        if (m.spectral_flatness_mean !== undefined) details.push(['Spectral Flatness', `${m.spectral_flatness_mean}`])
        if (m.duration_seconds !== undefined) details.push(['Duration', `${m.duration_seconds}s`])
    }

    for (const [label, value] of details) {
        if (y > 270) {
            doc.addPage()
            y = 20
        }
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(26, 26, 26)
        doc.text(label, 20, y)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(107, 114, 128)
        doc.text(String(value), 100, y)
        y += 6
    }

    y += 10
    doc.line(20, y, 190, y)
    y += 8

    // Disclaimer
    doc.setFontSize(8)
    doc.setTextColor(156, 163, 175)
    doc.text('This report was generated by Polyglot Ghost. Results are based on', 20, y)
    y += 4
    doc.text('statistical analysis and deep learning inference. Not legal evidence.', 20, y)

    // Footer bar
    doc.setFillColor(17, 17, 17)
    doc.rect(0, 282, 210, 15, 'F')
    doc.setFontSize(8)
    doc.setTextColor(255, 255, 255)
    doc.text('polyglotghost.com', 105, 290, { align: 'center' })

    // Save
    const fileName = `polyglot_ghost_report_${verdict.toLowerCase()}_${Date.now()}.pdf`
    doc.save(fileName)
}
